### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by bingxueyinlian** [mrjavicho/MvxPopupNavigation#1]
in CustomMvxFormsPagePresenter should add  if (currentPage != null) before currentPage.ViewModel.ViewDisappearing();

because ,if ShowPopup() in ViewModel's Initialize() will throw NullReferenceException

**Comment by mrjavicho** [comment]
@bingxueyinlian I'm very sorry, I wasn't really aware that someone else was using this. I have a couple of extra adjustments on my local machine, I'll create a new version with those and the null check  ;)

**Comment by mrjavicho** [comment]
Check added to v2.0.0
